spring.application.name=Notification
server.port=8082
spring.datasource.url = jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=thirth
spring.datasource.password=mypass
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
