spring.application.name=demo
server.port=8080
spring.datasource.url = jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=thirth
spring.datasource.password=mypass
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.jdbc.batch_size=50
